const mongoose = require('mongoose');

const ProfileSchema = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'users'
    },
    handle:{
        type:String,
        required:true,
        max:40
    },
    company:{
        type:String
    },
    location:{
        type:String
    },
    website:{
        type:String
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    bio:{
        type:String
    },

    githubUsername:{
        type:String
    },
    education:{
        type:[{
            school:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            fieldOfStudy:{
                type:String
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:String
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String
            }
        }]
    },
    experience:{
        type:[{
            title:{
                type:String,
                required:true
            },
            company:{
                type:String,
                required:true
            },
            location:{
                type:String
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:String
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String
            }
        }]
        },
        social:{
            youtube:{
                type:String
            },
            twitter:{
                type:String
            },
            linkedIn:{
                type:String
            },
            facebook:{
                type:String
            },
            instagram:{
                type:String
            },
        },
        Date:{
            type:Date,
            default:Date.now
        }
    });


const Profile = mongoose.model('Profile',ProfileSchema);

module.exports = {Profile};